Voss working
tacticalminky/cs225-final pull request #10
Opened 2022-11-26 18:06 UTC by EJVoss2

Got the importRatings function working

2022-11-27 03:09 UTC, RayaanAhmad commented
Rename the " animeidtouserid" variable to something shorter and with underscores, like "anime_ratings"

2022-11-28 22:41 UTC, tacticalminky requested changes
Some excess spaces, and it doesn't look like anime_graph will compile. Check return of function

2022-11-29 03:41 UTC, JacobGugala approved these changes

2022-11-29 03:45 UTC, tacticalminky approved these changes

2022-11-29 03:45 UTC, merged